import {COLORS} from "@/src/styles/colors";
import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  currentLocationMarker: {
    alignItems: "center",
  },
  currentLocationMarkerIcon: {
    width: 32,
    height: 32,
    borderRadius: 20,
    backgroundColor: COLORS.WHITE,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: COLORS.INFO,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  trackingMarker: {
    borderColor: COLORS.SUCCESS,
  },
  markerContainer: {
    alignItems: "center",
  },
  markerIcon: {
    width: 30,
    height: 30,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.WHITE,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  routeInfoCard: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 12,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  routeInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  routeInfoText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.DARK,
  },
  routeInfoSubtext: {
    fontSize: 12,
    color: COLORS.GRAY,
    marginTop: 4,
  },
  controls: {
    position: "absolute",
    right: 16,
    bottom: 100,
    gap: 12,
  },
  controlButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.WHITE,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  trackingActiveButton: {
    backgroundColor: COLORS.SUCCESS,
  },
  clearRouteButton: {
    backgroundColor: COLORS.ERROR || "#FF3B30",
  },
  trackingStatus: {
    position: "absolute",
    bottom: 40,
    left: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.SUCCESS,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 8,
  },
  trackingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.WHITE,
  },
  trackingText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.WHITE,
  },
  instructionsCard: {
    position: "absolute",
    bottom: 40,
    left: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    gap: 12,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  instructionsText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.DARK,
    fontWeight: "500",
  },
});
