import {COLORS} from "@/src/styles/colors";
import {Dimensions, Platform, StyleSheet} from "react-native";
const {width} = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: "#FAFAFA"},
  headerContainer: {
    paddingHorizontal: 12,
    paddingTop: Platform.OS === "android" ? 10 : 0,
    paddingBottom: 8,
    backgroundColor: COLORS.WHITE,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 10,
  },
  greetingSection: {flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8},
  greeting: {fontSize: 22, fontWeight: "800", color: COLORS.DARK},
  greetingSubtitle: {fontSize: 13, color: COLORS.GRAY},
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#FFF0F0",
    justifyContent: "center",
    alignItems: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: COLORS.ERROR,
    paddingHorizontal: 4,
    borderRadius: 8,
  },
  badgeText: {color: "white", fontSize: 10, fontWeight: "bold"},

  locationIconBg: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#FFF0F0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  locationTextContainer: {flex: 1},
  locationLabel: {fontSize: 11, color: COLORS.GRAY},
  locationAddress: {fontSize: 13, fontWeight: "600", color: COLORS.DARK},

  searchSection: {flexDirection: "row", gap: 8, marginBottom: 8},
  iconButton: {width: 50, height: 50, borderRadius: 8, justifyContent: "center", alignItems: "center"},
  filterButton: {backgroundColor: COLORS.PRIMARY, shadowColor: COLORS.PRIMARY, shadowOpacity: 0.3, elevation: 4},

  categoriesSection: {marginBottom: 12},
  categoriesContainer: {gap: 4, marginTop: 4},
  categoryItem: {alignItems: "center", width: 64},
  categoryIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    overflow: "hidden",
  },
  categoryIconContainerActive: {backgroundColor: COLORS.PRIMARY, borderWidth: 2, borderColor: "#FFD1D1"},
  categoryImage: {width: "100%", height: "100%", borderRadius: 4},
  categoryName: {fontSize: 11, fontWeight: "500", color: COLORS.DARK_GRAY, textAlign: "center"},
  categoryNameActive: {color: COLORS.PRIMARY, fontWeight: "700"},
  categoryItemActive: {transform: [{scale: 1.05}]},

  bannersContainer: {gap: 12, marginBottom: 12, paddingRight: 20, paddingLeft: 4},
  bannerCard: {
    width: width - 160,
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    height: 50,
    alignItems: "center",
  },
  bannerContent: {flexDirection: "row", alignItems: "center", gap: 12, flex: 1},
  bannerIconBg: {
    width: 36,
    height: 36,
    borderRadius: 20,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  bannerTitle: {fontSize: 16, fontWeight: "800", color: "white"},
  bannerSubtitle: {fontSize: 12, color: "rgba(255,255,255,0.9)"},

  tabContainer: {flexDirection: "row", backgroundColor: "#F3F4F6", padding: 4, borderRadius: 8, marginBottom: 4},
  tabButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
  },
  tabText: {fontSize: 12, fontWeight: "600", color: COLORS.GRAY},
  tabTextActive: {color: COLORS.WHITE},
  resultCountText: {fontSize: 11, color: COLORS.GRAY, textAlign: "center", marginTop: 4},

  map: {flex: 1},

  restaurantGrid: {gap: 16, marginTop: 10},
  restaurantCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },

  restaurantImageContainer: {height: 160, backgroundColor: COLORS.LIGHT_GRAY, position: "relative"},
  restaurantImage: {width: "100%", height: "100%"},
  placeholderImage: {alignItems: "center", justifyContent: "center"},

  ratingBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(0,0,0,0.6)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ratingText: {fontSize: 12, fontWeight: "700", color: COLORS.WHITE},

  closedOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  closedText: {fontSize: 16, fontWeight: "800", color: COLORS.WHITE, letterSpacing: 1},

  restaurantInfo: {padding: 12},
  restaurantName: {fontSize: 16, fontWeight: "700", color: COLORS.DARK, marginBottom: 4},
  metaRow: {flexDirection: "row", alignItems: "center"},
  metaItem: {flexDirection: "row", alignItems: "center", gap: 4},
  metaText: {fontSize: 12, color: COLORS.DARK_GRAY, fontWeight: "500"},
  metaDivider: {width: 1, height: 12, backgroundColor: COLORS.LIGHT_GRAY, marginHorizontal: 8},

  centerState: {flex: 1, justifyContent: "center", alignItems: "center", paddingVertical: 60},
  loadingText: {marginTop: 12, fontSize: 14, color: COLORS.GRAY},

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
    paddingBottom: 16,
  },
  modalContent: {
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.LIGHT_GRAY,
  },
  modalTitle: {fontSize: 18, fontWeight: "700", color: COLORS.DARK},
  modalBody: {padding: 20},
  modalRestaurantName: {fontSize: 20, fontWeight: "800", marginBottom: 4},
  modalMetaRow: {flexDirection: "row", alignItems: "center"},

  filterSectionTitle: {fontSize: 14, fontWeight: "700", color: COLORS.DARK, marginBottom: 12, marginTop: 8},
  filterOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 14,
    borderRadius: 8,
    backgroundColor: COLORS.LIGHT_GRAY,
    marginBottom: 8,
  },
  filterOptionRowActive: {backgroundColor: "#FFF0F0", borderWidth: 1, borderColor: COLORS.PRIMARY},
  filterOptionText: {fontSize: 14, color: COLORS.DARK},
  filterOptionTextActive: {fontWeight: "600", color: COLORS.PRIMARY},

  ratingFilterContainer: {flexDirection: "row", gap: 8, marginBottom: 8},
  ratingChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.LIGHT_GRAY,
    borderWidth: 1,
    borderColor: COLORS.LIGHT_GRAY,
  },
  ratingChipActive: {backgroundColor: COLORS.PRIMARY, borderColor: COLORS.PRIMARY},
  ratingChipText: {fontSize: 13, fontWeight: "600", color: COLORS.DARK},
  ratingChipTextActive: {color: COLORS.WHITE},

  priceInputsContainer: {flexDirection: "row", alignItems: "center", gap: 8},
  priceInputWrapper: {flex: 1},
  priceSeparator: {fontSize: 18, color: COLORS.GRAY, fontWeight: "600", marginBottom: 16},

  modalFooter: {
    flexDirection: "row",
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.LIGHT_GRAY,
  },

  promotionModalContent: {
    backgroundColor: COLORS.WHITE,
    marginHorizontal: 20,
    borderRadius: 16,
    padding: 24,
    maxWidth: 400,
    alignSelf: "center",
  },
  promotionModalHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  promoIconLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  closeButton: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.LIGHT_GRAY,
    justifyContent: "center",
    alignItems: "center",
  },
  promoCodeSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.LIGHT_GRAY,
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  promoCodeText: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.DARK,
    letterSpacing: 1,
  },
  copyButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: COLORS.WHITE,
  },
  copyText: {fontSize: 13, fontWeight: "600", color: COLORS.PRIMARY},
  promoDescription: {
    fontSize: 14,
    color: COLORS.GRAY,
    lineHeight: 20,
    marginBottom: 20,
  },
  promoDetailsContainer: {
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    padding: 16,
    gap: 12,
  },
  promoDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  promoDetailLabel: {
    fontSize: 14,
    color: COLORS.DARK_GRAY,
    flex: 1,
  },
  promoDetailValue: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.DARK,
  },

  activeIndicator: {
    position: "absolute",
    left: 4,
    top: 4,
    bottom: 4,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 10,
    shadowColor: COLORS.PRIMARY,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 0,
  },

  tabWrapper: {
    flex: 1,
    zIndex: 1,
  },
  locationChevronBg: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFF0F0",
    alignItems: "center",
    justifyContent: "center",
  },
  filterActiveDot: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#FFB800",
    borderWidth: 1,
    borderColor: COLORS.WHITE,
  },

  resultCountContainer: {
    paddingVertical: 4,
  },

  locationSection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.WHITE,
    padding: 4,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#F0F0F0",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
});

export default styles;
